### ISSUE TITLE
tettelin core/pan estimate fails with cryptic "error"

### ISSUE THREAD

**Issue by alexweisberg** [eead-csic-compbio/get_homologues#10]
I am trying to run the Tettelin estimate for pan- and core- genome size on a set of genomes. Using the following command:
get_homologues.pl -d ./genomestettelin -c -M
The analysis appears to be running and gets this far:
 ~/Software/get_homologues-x86_64-20160413/get_homologues.pl -i 0 -d ./genomestettelin -o 0 -e 0 -f 0 -r 0 -t all -c 1 -z 0 -I 0 -m local -n 2 -M 1 -G 0 -P 0 -C 75 -S 1 -E 1e-05 -F 1.5 -N 0 -B 50 -b 0 -s 0 -D 0 -g 0 -a '0' -x 0 -R 0 -A 0

 results_directory=~/gethomologues/genomestettelin_homologues
 parameters: MAXEVALUEBLASTSEARCH=0.01 MAXPFAMSEQS=250 BATCHSIZE=100 KEEPSCNDHSPS=1

 checking input files...
 02-815.gbk 5656
 02-816c.gbk 5648`

... etc ...

 parsing blast result! (~/gethomologues/genomestettelin_homologues/tmp/all.blast , 8.4e+03MB)
 parsing file finished

 creating indexes, this might take some time (lines=1.41e+08) ...

 construct_taxa_indexes: number of taxa found = 62
 number of file addresses/BLAST queries = 3.2e+05

 genome composition report (samples=10,permutations=3.147e+85,seed=0)
 genomic composition parameters: MIN_PERSEQID_HOM=0 MIN_COVERAGE_HOM=20 (set in lib/marfil_homology.pm)
 genome order:

... etc ...

 identifying orthologs between RS1D5.gbk and UNC23MFCrub1.1.gbk (0)
 3182 sequences

 identifying inparalogs in RS1D5.gbk
 72 sequences

 identifying inparalogs in UNC23MFCrub1.1.gbk
 49 sequences

 running MCL (inflation=1.5) ...
 running MCL finished

 find_OMCL_clusters: parsing clusters (~/gethomologues/genomestettelin_homologues/tmp/all_ortho.mcl)

 sample 0 (02-815.gbk | 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,...)
 adding 02-815.gbk: core=5490 pan=5490
 finding homologs between 02-816c.gbk and 02-815.gbk
ARRAY(0x582c7c20)
ARRAY(0x57397460)
ARRAY(0x7b96fe98)
ARRAY(0x83357218)
ARRAY(0x93e73ca8)
ARRAY(0xbbf44b68)
ARRAY(0x4f6f3628)
ARRAY(0xacd7a200)
...
and so on for 4GB of log file. The analysis has been running for about a week now but I'm fairly sure it will not finish at this point.

**Comment by eead-csic-compbio** [comment]
Hi Alex,
thanks for your feedback. It seems you are running get_homologues with the default two cores, right? How many CPU cores can you take? If your Linux box or laptop has more cores, say 8, you can allocate them with -n 8. This would speed up the analysis, as you are doing 62x62 BLAST searches. You can speed it up further with -X to call DIAMOND instead of BLASTP. Of course, you would have to update the software to the current version, which I strongly recomend as you are missing a few bug fixes. 

Now, coming back to your job, it looks like BLAST was completed correctly from your output, but there are issues with homology calling with OMCL. So I would remove your _homologues/tmp folder an re-run again your command with the update software. Keep an eye on the size of the BLAST outfiles, when they are being sorted, as that will tell you whether some of the jobs failed. If you have further issues let us know, cheers, Bruno 

since you are processing 62 genomes,

**Comment by alexweisberg** [comment]
Hi Bruno,
Thank you for the response. I have previously successfully run get_homologues on this dataset to completion with a typical analysis, however the problem occurs when I want to do a genome composition analysis (add option "-c"). I deleted the tmp folder as you suggested and am re-running it now. 

As an aside, is there any way to do the genome composition analysis using a previous run? I have a get_homologues folder of MCL clustered sequences. Is it possible to parse the output from the previous run and do the genome composition analysis without having to redo the blast searches and clustering?

**Comment by eead-csic-compbio** [comment]
Hi Alex,
I just went back to test that release (get_homologues-x86_64-20160413) and found out that indeed that version printed all those "ARRAY(...)" when it shouldn't. So please update your software and re-run on the same folders, so that you don't have to run BLAST again, ok?
So, getting to your second question. Yes you can perform a genome composition analysis (-c) using a previous run provided that you kept the *_homologues folder. That folder should contain old BLAST results which can be recycled provided that you are using version > v.2.0.1.
Cheers, Bruno
