### ISSUE TITLE
(-S) parameter affect the output of BDBH but not COG or OMCL

### ISSUE THREAD

**Issue by MostafaYA** [eead-csic-compbio/get_homologues#11]
Hi, 
Why change the value of (-S) parameter results in a big difference only with the BDBH algorithm but not with COG or OMCL while estimating the core genome?
When using BDBH, (-S 1 default) results in 2422 cluster,  (-S 90) results in 2319 cluster, (-S 95) results in 1916 clusters.
For OMCL and COG, both result in 2412 and 2404 respectively, regardless to the (-S) value. 
Regards,

**Comment by eead-csic-compbio** [comment]
Hi, 
parameter -S is the minimum % sequence identity computed by BLAST between a pair of sequences in order to be called orthologues. As summarized in the command line help (-h), it only affects BDBH and OMCL algorithms, not COG. 
Please double-check your OMCL result (-M), as in this case the number of clusters should change. I just re-tested with sample data and it does as expexted,
thanks for the feedback,
Bruno

**Comment by MostafaYA** [comment]
Hi, 
I have tried it again with different -S values and you are right. The output changes. It should be something went wrong with my initial runs. But could you please explain why COG should not make any difference?

**Comment by eead-csic-compbio** [comment]
That's because the COG triangles algorithm, as embedded in GET_HOMOLOGUES, does not consider sequence identity as an input parameter. Briefly, it considers triplets of reciprocal best hits with enough alignment coverage to be orthologue candidates, regardless of how similar their sequences are, hoe this helps, Bruno
