### ISSUE TITLE
flag -P in parse_pangenome_matrix.pl

### ISSUE THREAD

**Issue by MostafaYA** [eead-csic-compbio/get_homologues#14]
Hi, 

I am still having some concerns regarding the command `parse_pangenome_matrix.pl`. 
The question that I am trying to answer is “what are the genes that present in any of gp A genomes (or a percentage like 50 % of gp A) but absent in all of gp B genomes (100 %). 

By default, flag –P is invoked, and making a single cutoff value to both groups at once, and at the end, we get the genes present in all A, absent in all B. Relaxing the –P value will result in some shared genes between the gps.

My inquiry is, 
Is that possible to completely disable the -P option, and so I can rely on the –S parameter instead , or alternatively, it would be great if I can set a cutoff value to each gp separately, like –P_gpA 50 & -P_gpB 100

**Comment by eead-csic-compbio** [comment]
Hi Mostafa,
I am currently away so I cannot add those features, but you might want to try options -a -B to look for genes absent in -B genomes (no -A list required here). Let me know if this works for you, Bruno

**Comment by MostafaYA** [comment]
Hi Bruno, 
Thanks for your suggestion. It tried -a -B, which gives me a list of 739 genes and when I add -S for some more refinement, the list was reduced to 201 genes. so it seems it worked without adding more additional features. 
I have a question here (a bit away from get_homologues), with this list of genes, Is it safe to go and announce the genes are specific to one gp, not the other. or What confirmation tool do you recommend me to go with, may be blastp or something like that.

**Comment by eead-csic-compbio** [comment]
A first check you can do with script make_nr_pangenome_matrix.pl , which will compute a non-redundant pangenome matrix and can also match the resulting clusters to an external collection of sequences. This way it is possible to make sure whether genes which were apparently missing in a group of genomes/accessions have a close paralogue which might be taking that role, even if sequence identity is a bit lower.

I guess the ultimate check would be to take the raw genomic reads of the genomes where some loci are missing and map them to those genes confirm that they really are absent, instead of being left out of the assembly or gene annotation.

I hope this helps
