### ISSUE TITLE
Clustering orthologous sequences using multiple threads?

### ISSUE THREAD

**Issue by jspatane** [eead-csic-compbio/get_homologues#32]
Dear Get_Homologues developers,

I've been using the program a lot. Recently I noticed that the step of " # clustering orthologous sequences" proceeds serially... if this step could use multiple threads simultaneously, the speed bottleneck could be reduced substantially, I guess. Could it be implemented in a forthcoming version?

Best,

Jose

**Comment by eead-csic-compbio** [comment]
Thanks for the comment. Option -m cluster does that, but you might have to install gris engine. Read more at http://eead-csic-compbio.github.io/get_homologues/manual/manual.html#SECTION00033000000000000000

**Comment by eead-csic-compbio** [comment]
I just realised that the correct URL of Son of Grid Engine is now:
https://arc.liv.ac.uk/downloads/SGE/releases/
and also 
https://sourceforge.net/projects/gridengine
Bruno

**Comment by alexweisberg** [comment]
To add to this, is it possible to rerun the clustering step using cluster mode (-m cluster) to redo clustering runs that failed? I previously ran in cluster mode and a number of ortholog comparisons failed due to network issues. I would like to rerun those failed comparisons without rerunning the rest of them. Is this currently possible? Thanks!

**Comment by eead-csic-compbio** [comment]
Hi Alex,
that is certainly possible. To make sure that corrupted results do not affect the outcome I would remove the _homologues/tmp folder and re-run. Please let us know how it goes, Bruno
