### ISSUE TITLE
run time

### ISSUE THREAD

**Issue by mjfi2sb3** [eead-csic-compbio/get_homologues#7]
Hi,

I would like to run get_homologues on a dataset of over 2000 microbial genomes. Is there is any way I can achieve this in a reasonable amount of time.

I have at my disposable a large computer cluster.

Best,
/SB

**Comment by eead-csic-compbio** [comment]
Hi Salim,
I have never analyzed such a great dataset, so I can't promise anything.
Last week I did analyze 350 bacterial genomes of 4-5K genes each in
my workstation simulating a GridEngine cluster of 30 nodes in less
than 2 days. However, this generated over 300GB of files.
There are four main steps to be considered: i) the sequence similarity
searches, ii) sorting and indexing the BLAST/DIAMOND results, iii)
calling inparalogues and orthologues and, iv) running mcl.
In your case, steps i and iii scale well and you should be fine if you
have a large GridEngine cluster (option -m cluster), particularly if
you choose option -X which uses DIAMOND instead of BLASTP. DIAMOND is
faster than BLASTP for large sequence numbers at the cost of being
slightly less sensitive, added to the fact that in GET_HOMS only two
runs are required per genome, instead of all vs all with BLASTP.
Instead, steps ii and iv should take some time as they don't scale
that well and you'll have a large volume of DIAMOND results, but
nevertheless they should complete ok if you don't run out of isk space
or RAM.
Please let us know how it goes if you decide to try,
best wishes,
Bruno
