### ISSUE TITLE
program Killed while identifying inparalogs in get_homologous 

### ISSUE THREAD

**Issue by Dimpledavray287** [eead-csic-compbio/get_homologues#71]
HI,

I am working on pangenome analysis of Lactobacillus species, where i am comparing genome of chromosomes with the plasmid genome. I have pulled all the CDSs associated with chromosomes for all the strains of one species (105 strains) and another files of CDSs of plasmids (385 plasmids) which resides under these strains. Total CDSs of chromosomes were 310855 and for plasmids 15698. To know the overall core CDSs between chromosomes and plasmids I had executed the given below command.
./get_homologues.pl -n12 -M -d compare . The blast executed fine and clustering orthologous sequences also executed fine. The program killed while identifying inparalogs in chromosomes. I have checked the space, it almost 400 GB free. I have checked the same analysis for small data it worked fine. 

Output result 

# ./get_homologues.pl -i 0 -d compare -o 0 -X 0 -e 0 -f 0 -r 0 -t all -c 0 -z 0 -I 0 -m local -n 12 -M 1 -G 0 -p 0 -C 75 -S 1 -E 1e-05 -F 1.5 -N 0 -B 50 -b 0 -s 0 -D 0 -g 0 -a '0' -x 0 -R 0 -A 0 -P 0

# version 10032020
# results_directory=/home/dimple/Software/get_homologues-3.3.3/compare_homologues
# parameters: MAXEVALUEBLASTSEARCH=0.01 MAXPFAMSEQS=250 BATCHSIZE=100 KEEPSCNDHSPS=1
# diamond job:0

# checking input files...
# Chro.faa 310855
# Plas.faa 15698

# 2 genomes, 326553 sequences

# taxa considered = 2 sequences = 326553 residues = 98098627 MIN_BITSCORE_SIM = 20.7

# mask=Plas_f0_alltaxa_algOMCL_e0_ (_algOMCL)

# running makeblastdb with /home/dimple/Software/get_homologues-3.3.3/compare_homologues/Chro.faa.fasta

# running makeblastdb with /home/dimple/Software/get_homologues-3.3.3/compare_homologues/Plas.faa.fasta

# running BLAST searches ...
# done

# concatenating and sorting BLAST/DIAMOND results...
# sorting _Chro.faa results (9.7e+03MB)
# sorting _Plas.faa results (3.3e+02MB)
# done

# parsing blast result! (/home/dimple/Software/get_homologues-3.3.3/compare_homologues/tmp/all.blast , 1e+04MB)
# parsing file finished

# creating indexes, this might take some time (lines=1.68e+08) ...

# construct_taxa_indexes: number of taxa found = 2
# number of file addresses/BLAST queries = 3.3e+05

# clustering orthologous sequences

# identifying orthologs between Chro.faa and Plas.faa (0)
# 209541 sequences

# identifying inparalogs in Chro.faa
Killed
dimple@dimple-VirtualBox:~/Software/get_homologues-3.3.3$ 

Kindly let me know if you need any other information

**Comment by eead-csic-compbio** [comment]
Hi @Dimpledavray287 , it seems your operating system killed the job, probably for using too much RAM. This could happen also on HPC clusters if the queue you are using has a limit on the duration of jobs.
Possible solutions:

1) Move the job to a machine with larger RAM. You should copy the input and _homologues folder and the job should be picked up where it stopped.

2) If 1 is not an option you can try option -s ; this reduces the memory imprint of the job and thus frees RAM at the cost of being slightly slower than the default

3) Set up your machine as HPC cluster with slurm or GridEngine as explained in the documentation. That way you can use -m cluster so that the orthologues and inparalogues jobs are run in parallel

Hope this helps,
Bruno

**Comment by Dimpledavray287** [comment]
Thanks . I will do as you suggested and update you later.
