### ISSUE TITLE
Phylogenetic tree not showing strain name

### ISSUE THREAD

**Issue by apoorva004** [eead-csic-compbio/get_homologues#95]
Hi @eead-csic-compbio, 

- I have been trying to construct the phylogenetic tree, but it does now show names of the strains. Instead some weird characters are being seen in the output. Can yiu guide me what could be the reason behind this? I got names of my strains in pan genome matrix (tab file) and ANI output (heatmap). Attached is the photo of output. 
![Phylogenetic output](https://user-images.githubusercontent.com/87976649/159221450-c94fb844-5de7-4eac-90fd-a4e38f2d405d.PNG)

**Comment by eead-csic-compbio** [comment]
Hi @apoorva004 @vinuesa ,
as far as I remember we did that way because PHYLIP required labels to be of the same fixed length?
You can see a similar example in the [manual](http://eead-csic-compbio.github.io/get_homologues/manual/manual.html#SECTION00059000000000000000)

You can check the actual taxa names by comparing pangenome_matrix_t0.phylip and pangenome_matrix_t0.fasta

Let me know if this helps,
Bruno
